window.UMI_CONTENT = {
  aboutTitle:"ABOUT",
  aboutSubtitle:"Umiについて",
  aboutWhyTitle:"人は、小さな変化によって人生の可能性を広げられる。",
  aboutWhyText:"私たちは、その無限の可能性を信じている。毎日の中にある小さな変化が、人生をより自由に、より面白くしていく。そのきっかけをつくることが、Umiの原点です。",
  storyTitle:"海は、一滴の水から始まる。",
  storyText:"私たちは、その一滴のきっかけを創り続ける。",
  philoJp:"Umiの理念",
  whyLabel:"WHY",
  whySub:"なぜ、私たちは存在するのか",
  whyText:"一人ひとりの人生には、まだ見ぬ可能性がある。\nその可能性に光をあて、\n自分らしく輝けるきっかけを届けたい。\nそれが、Umiの存在意義です。",
  visionLabel:"VISION",
  visionSub:"私たちが目指す未来",
  visionText:"ユニークで面白い人生を、あたりまえに。\n誰もが自分らしく、心からワクワクできる\n世の中をつくります。",
  missionLabel:"MISSION",
  missionSub:"私たちが実現すること",
  missionText:"人生を美しく彩るプロダクトや体験を通して、\n一人ひとりの可能性を解き放つサポートをする。\nそして、新しい価値を生み出し続けます。",
  brandTitle:"BRAND",
  brandSubtitle:"ブランド",
  brandComing:"COMING SOON",
  brandName:"mormee",
  brandTag:"Good morning, me.",
  brandCopy:"",
  companyTitle:"COMPANY",
  companySubtitle:"会社概要",
  companyName:"Umi株式会社",
  companyBusiness:"化粧品・美容関連商品の企画、開発、販売",
  companyWebsite:"umi-beauty.com"
};